import z from "zod"

/**
 * Capability policy for process-backed tools.
 *
 * The process boundary deals in logical capability IDs rather than raw
 * environment variable names.  A capability only becomes visible when all
 * three inputs agree: the one-shot execution request, the loaded skill's
 * declaration, and the current agent profile grant.  This module is kept
 * independent of Config/Skill so it can be used at both schema and spawn
 * boundaries without introducing a dependency cycle.
 */

export const CAPABILITY_ENV = {
  "llm:anthropic": ["ANTHROPIC_API_KEY"],
  "llm:openai": ["OPENAI_API_KEY"],
  "llm:gemini": ["GOOGLE_GENERATIVE_AI_API_KEY", "GOOGLE_API_KEY", "GEMINI_API_KEY"],
  "llm:openrouter": ["OPENROUTER_API_KEY", "OPENROUTER_BASE_URL"],
  "llm:together": ["TOGETHER_API_KEY"],
  "llm:groq": ["GROQ_API_KEY"],
  "llm:fireworks": ["FIREWORKS_API_KEY"],
  "llm:mistral": ["MISTRAL_API_KEY"],
  "llm:deepseek": ["DEEPSEEK_API_KEY"],
  "llm:cerebras": ["CEREBRAS_API_KEY"],
  "llm:xai": ["XAI_API_KEY"],
  "compute:modal": ["MODAL_TOKEN_ID", "MODAL_TOKEN_SECRET"],
  "compute:tinker": ["TINKER_API_KEY", "TINKER_BASE_URL"],
  "compute:huggingface": ["HF_TOKEN", "HUGGING_FACE_HUB_TOKEN"],
  "compute:wandb": ["WANDB_API_KEY"],
  "compute:lambda": ["LAMBDA_API_KEY", "LAMBDA_LABS_API_KEY"],
  "compute:runpod": ["RUNPOD_API_KEY"],
  "compute:prime": ["PRIME_INTELLECT_API_KEY"],
  "compute:tensorpool": ["TENSORPOOL_API_KEY"],
  "compute:vast": ["VAST_API_KEY"],
} as const

const CAPABILITY_IDS = Object.keys(CAPABILITY_ENV) as [keyof typeof CAPABILITY_ENV, ...(keyof typeof CAPABILITY_ENV)[]]

/** Stable, centrally allowlisted logical IDs. */
export const CapabilityID = z.enum(CAPABILITY_IDS)
export type CapabilityID = z.infer<typeof CapabilityID>

/** Canonical source IDs are generated by Skill discovery, never by a skill. */
export const SourceID = z
  .string()
  .regex(
    /^(?:bundled|cached|installed|learned|user|system|project|claude|local):[A-Za-z0-9][A-Za-z0-9._/-]*$/,
    "Expected a canonical skill source ID (for example bundled:name or installed:namespace/name)",
  )
export type SourceID = z.infer<typeof SourceID>

/** Capability arrays reject duplicates and all non-canonical IDs. */
export const CapabilityList = z
  .array(CapabilityID)
  .superRefine((values, ctx) => {
    const seen = new Set<string>()
    for (const [index, value] of values.entries()) {
      if (seen.has(value)) {
        ctx.addIssue({ code: z.ZodIssueCode.custom, path: [index], message: `Duplicate capability "${value}"` })
      }
      seen.add(value)
    }
  })
export type CapabilityList = z.infer<typeof CapabilityList>

const SkillGrant = z.object({ source: SourceID, capabilities: CapabilityList }).strict()

/**
 * Agent-side upper bounds.  The object form is the public config format:
 * `{ direct: [], skills: { "bundled:name": ["llm:openrouter"] } }`.
 * An entry-array form is accepted too, allowing a JSON loader to detect
 * duplicate source records instead of silently losing one during parsing.
 */
export const CapabilityGrants = z
  .object({
    direct: CapabilityList.default([]),
    skills: z.union([z.record(SourceID, CapabilityList), z.array(SkillGrant)]).default({}),
  })
  .strict()
  .transform((value) => {
    if (!Array.isArray(value.skills)) return value
    const skills: Record<string, CapabilityList> = {}
    for (const grant of value.skills) {
      if (skills[grant.source]) {
        throw new CapabilityPolicyError("duplicate skill source grant", { source: grant.source })
      }
      skills[grant.source] = grant.capabilities
    }
    return { direct: value.direct, skills }
  })
export type CapabilityGrants = { direct: CapabilityList; skills: Record<string, CapabilityList> }

/** Frontmatter declaration (a declaration is not an authorization). */
export const SkillCapabilities = CapabilityList
export type SkillCapabilities = z.infer<typeof SkillCapabilities>

/** Additive execution metadata accepted by Bash/notebook/rkernel. */
export const Execution = z
  .object({
    skill: SourceID.optional(),
    capabilities: CapabilityList.default([]),
  })
  .strict()
export type Execution = z.infer<typeof Execution>

export const CapabilityPolicyError = class extends Error {
  readonly code = "CAPABILITY_DENIED"
  readonly details: Record<string, unknown>

  constructor(message: string, details: Record<string, unknown> = {}) {
    super(message)
    this.name = "CapabilityPolicyError"
    this.details = details
  }
}

export interface SourceProof {
  sourceID: SourceID
  digest: string
  declared: CapabilityList
  loaded: boolean
  permissionApproved: boolean
  sessionID: string
  turnID: string
  agent: string
}

export interface GrantProof {
  sessionID: string
  turnID: string
  agent: string
  sourceID?: SourceID
  digest?: string
  capabilities: CapabilityList
}

export interface ResolveInput {
  /** Current invocation identity; grants must not be replayed across any of it. */
  sessionID: string
  turnID: string
  agent: string
  grants?: unknown
  execution?: unknown
  /** Exact source loaded and permission-approved during this turn. */
  source?: SourceProof
  /** Optional signed/ephemeral grant binding produced by bindGrant(). */
  grant?: GrantProof
}

export interface Decision {
  allowed: boolean
  capabilities: CapabilityID[]
  env: string[]
  denied: string[]
  reason?: string
  /** Safe telemetry fields; never includes values. */
  observations: { capability: string; env: string[]; allow: boolean }[]
}

function parsedGrants(input: unknown): CapabilityGrants {
  const parsed = CapabilityGrants.safeParse(input ?? {})
  if (!parsed.success) {
    throw new CapabilityPolicyError("invalid subprocess capability grant", { issues: parsed.error.issues })
  }
  return parsed.data as CapabilityGrants
}

function parsedExecution(input: unknown): Execution {
  const parsed = Execution.safeParse(input ?? {})
  if (!parsed.success) {
    throw new CapabilityPolicyError("invalid subprocess capability request", { issues: parsed.error.issues })
  }
  return parsed.data
}

function envFor(values: readonly string[]): string[] {
  return Array.from(new Set(values.flatMap((value) => CAPABILITY_ENV[value as CapabilityID] ?? [])))
}

function fail(reason: string, requested: CapabilityID[] = []): Decision {
  const env: string[] = []
  return {
    allowed: false,
    capabilities: [],
    env,
    denied: requested,
    reason,
    observations: requested.map((capability) => ({ capability, env: [...(CAPABILITY_ENV[capability] ?? [])], allow: false })),
  }
}

function sameIdentity(input: ResolveInput, proof: { sessionID: string; turnID: string; agent: string }): boolean {
  return input.sessionID === proof.sessionID && input.turnID === proof.turnID && input.agent === proof.agent
}

/**
 * Evaluate without spawning.  Parsing errors are represented as a denied
 * decision; callers that need fail-fast semantics should use resolve().
 */
export function evaluatePolicy(input: ResolveInput): Decision {
  try {
    const execution = parsedExecution(input.execution)
    const grants = parsedGrants(input.grants)
    if (execution.capabilities.length === 0) {
      return { allowed: true, capabilities: [], env: [], denied: [], observations: [] }
    }

    if (execution.skill) {
      const source = input.source
      if (!source || source.sourceID !== execution.skill) return fail("skill source is not loaded in this turn", execution.capabilities)
      if (!source.loaded || !source.permissionApproved) return fail("skill permission was not approved", execution.capabilities)
      if (!source.digest) return fail("skill digest is missing", execution.capabilities)
      if (!sameIdentity(input, source)) return fail("skill proof identity mismatch", execution.capabilities)
      const granted = grants.skills[execution.skill]
      if (!granted) return fail("agent has no grant for this skill source", execution.capabilities)
      if (!input.grant) return fail("source grant binding is missing", execution.capabilities)
      if (!sameIdentity(input, input.grant)) return fail("grant identity mismatch", execution.capabilities)
      if (input.grant.sourceID !== execution.skill || input.grant.digest !== source.digest) {
        return fail("grant source or digest mismatch", execution.capabilities)
      }
      const effective = execution.capabilities.filter(
        (capability) => source.declared.includes(capability) && granted.includes(capability) && input.grant!.capabilities.includes(capability),
      )
      if (effective.length !== execution.capabilities.length) {
        return fail("requested capability is not declared and granted", execution.capabilities.filter((x) => !effective.includes(x)))
      }
      return {
        allowed: true,
        capabilities: effective,
        env: envFor(effective),
        denied: [],
        observations: effective.map((capability) => ({ capability, env: [...CAPABILITY_ENV[capability]], allow: true })),
      }
    }

    const direct = grants.direct
    if (input.grant) {
      if (!sameIdentity(input, input.grant)) return fail("grant identity mismatch", execution.capabilities)
      if (input.grant.sourceID || input.grant.digest) return fail("direct grants cannot carry a skill source", execution.capabilities)
    }
    const effective = execution.capabilities.filter(
      (capability) => direct.includes(capability) && (input.grant ? input.grant.capabilities.includes(capability) : true),
    )
    if (effective.length !== execution.capabilities.length) {
      return fail("requested capability is not in the direct agent grant", execution.capabilities.filter((x) => !effective.includes(x)))
    }
    return {
      allowed: true,
      capabilities: effective,
      env: envFor(effective),
      denied: [],
      observations: effective.map((capability) => ({ capability, env: [...CAPABILITY_ENV[capability]], allow: true })),
    }
  } catch (error) {
    if (error instanceof CapabilityPolicyError) return fail(error.message)
    return fail("invalid subprocess capability policy input")
  }
}

/** Resolve and fail closed before a process/kernel lookup or spawn. */
export function resolvePolicy(input: ResolveInput): Decision {
  const decision = evaluatePolicy(input)
  if (!decision.allowed) throw new CapabilityPolicyError(decision.reason ?? "subprocess capability denied", { denied: decision.denied })
  return decision
}

/** Bind a profile grant to one turn/source so it cannot be replayed elsewhere. */
export function bindGrantPolicy(input: {
  sessionID: string
  turnID: string
  agent: string
  sourceID?: SourceID
  digest?: string
  capabilities: unknown
}): GrantProof {
  const parsed = CapabilityList.safeParse(input.capabilities)
  if (!parsed.success) throw new CapabilityPolicyError("invalid capability grant binding", { issues: parsed.error.issues })
  if ((input.sourceID && !input.digest) || (!input.sourceID && input.digest)) {
    throw new CapabilityPolicyError("source grants require both sourceID and digest")
  }
  return {
    sessionID: input.sessionID,
    turnID: input.turnID,
    agent: input.agent,
    ...(input.sourceID ? { sourceID: input.sourceID } : {}),
    ...(input.digest ? { digest: input.digest } : {}),
    capabilities: parsed.data,
  }
}

export const capabilityEnv = envFor
export const capabilityToEnv = envFor
export const parseCapabilityGrants = parsedGrants
export const parseExecution = parsedExecution
export const evaluate = evaluatePolicy
export const resolve = resolvePolicy
export const bindGrant = bindGrantPolicy

export namespace CapabilityPolicy {
  export const ids = CapabilityID
  export const sources = SourceID
  export const list = CapabilityList
  export const grants = CapabilityGrants
  export const execution = Execution
  export const env = CAPABILITY_ENV
  export const evaluate = evaluatePolicy
  export const resolve = resolvePolicy
  export const bindGrant = bindGrantPolicy
}
