import { existsSync } from "fs"
import path from "path"
import { randomBytes } from "crypto"
import type { Subprocess } from "bun"
import { UI } from "../cli/ui"

/**
 * Research Graph sidecar supervisor.
 *
 * Lifecycle model:
 *
 *   idle -> starting -> ready -> stopping -> idle
 *   starting -> failed -> idle
 *   ready -> exited -> idle
 *
 * One managed child per MedHorizon process. Readiness requires an exact
 * service/protocol match plus a Bearer capability accepted by the child; the
 * capability is generated by the parent (>= 256 bits), passed to the child
 * ONLY as `RESEARCH_GRAPH_MANAGED_CAPABILITY`, and never printed.
 *
 * `createResearchGraphSupervisor()` returns an ISOLATED instance per caller or
 * test. The production exports delegate to one module singleton so tests never
 * mutate the process-wide supervisor.
 */

export const DEFAULT_READY_TIMEOUT_MS = 15000
const MIN_READY_TIMEOUT_MS = 1000
const MAX_READY_TIMEOUT_MS = 120000
const EXPECTED_SERVICE = "research-graph"
const EXPECTED_PROTOCOL = 1
const CAPABILITY_BYTES = 32 // >= 256 bits
const DISCOVERY_BYTE_BUDGET = 2048
const HEALTH_POLL_MS = 200
const HEALTH_POLL_TIMEOUT_MS = 1000
const STOP_GRACE_MS = 2000
const STOP_FALLBACK_MS = 2000
const KILL_REAP_MS = 1500
const LEGACY_FIXED_PORT = 8000
const LEGACY_REMOVAL_VERSION = "v0.5.0"
const WARNINGS_MAX = 16

export type SupervisorState = "idle" | "starting" | "ready" | "stopping" | "failed" | "exited"

export type DiagnosticCode =
  | "disabled"
  | "no_binary"
  | "spawn_failed"
  | "discovery_timeout"
  | "discovery_too_large"
  | "discovery_eof"
  | "extra_discovery_record"
  | "malformed_discovery"
  | "identity_mismatch"
  | "protocol_mismatch"
  | "capability_rejected"
  | "connection_refused"
  | "health_check_failed"
  | "child_exited"
  | "legacy_fallback"

export type Diagnostic = {
  code: DiagnosticCode
  message: string
  /** Lifecycle state when the diagnostic was recorded. */
  state?: SupervisorState
  /** Endpoint origin when known (discovery/health probes). */
  endpoint?: string
  /** Milliseconds since the current start() began. */
  elapsedMs?: number
  /** Last recorded child exit, if any. */
  lastExit?: Exit | null
}

export type Endpoint = {
  origin: string
  api: string
  token: string
  service: string
  version: string
  protocol: number
}

export type Exit = { code: number | null; signal: string | null }

export type StartResult =
  | { ok: true; endpoint: Endpoint; mode: "managed" | "external" }
  | { ok: false; diagnostic: Diagnostic }

export type SupervisorSnapshot = {
  state: SupervisorState
  generation: number
  endpoint: Endpoint | null
  lastExit: Exit | null
  lastProbe: Diagnostic | null
  warnings: Diagnostic[]
}

export type ResearchGraphSupervisor = {
  bind(): void
  start(): Promise<StartResult>
  stop(): Promise<void>
  snapshot(): SupervisorSnapshot
}

type Child = { proc: Subprocess; generation: number }

type Discovery = { port: number; service: string; version: string; protocol: number }

function diag(code: DiagnosticCode, message?: string): Diagnostic {
  return { code, message: message ?? code }
}

function isDiagnostic(err: unknown): err is Diagnostic {
  return typeof err === "object" && err !== null && typeof (err as Diagnostic).code === "string"
}

function asDiagnostic(err: unknown, scrub: (text: string) => string): Diagnostic {
  if (isDiagnostic(err)) return err
  return diag("health_check_failed", scrub(sanitize(String(err))))
}

function sanitize(text: string): string {
  let clean = ""
  for (const ch of text) {
    const code = ch.codePointAt(0) ?? 0
    clean += code < 32 || code === 127 ? " " : ch
  }
  clean = clean.trim()
  return clean.length > 200 ? clean.slice(0, 200) + "…" : clean
}

export const REDACTED = "[redacted]"

/**
 * Scrub every known secret out of diagnostic text: raw secret occurrences,
 * `Authorization: Bearer <secret>` header values, and any remaining
 * `Authorization: Bearer ...` header value are replaced with a placeholder so a
 * captured log can never carry the capability or an operator token.
 */
export function redact(text: string, secrets: Iterable<string>): string {
  let clean = text
  for (const secret of secrets) {
    if (!secret) continue
    clean = clean.split(`Bearer ${secret}`).join(REDACTED)
    clean = clean.split(secret).join(REDACTED)
  }
  clean = clean.replace(/Authorization:\s*Bearer\s+\S+/g, `Authorization: ${REDACTED}`)
  return clean
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms))
}

function generateCapability(): string {
  return randomBytes(CAPABILITY_BYTES).toString("base64url")
}

/** Parse and clamp `RESEARCH_GRAPH_READY_TIMEOUT_MS` (1s-120s, else default). */
export function resolveReadyTimeoutMs(raw: string | undefined): number {
  if (!raw) return DEFAULT_READY_TIMEOUT_MS
  const n = Number(raw)
  if (!Number.isInteger(n)) return DEFAULT_READY_TIMEOUT_MS
  return Math.min(MAX_READY_TIMEOUT_MS, Math.max(MIN_READY_TIMEOUT_MS, n))
}

function exitDescription(code: number | null): string {
  if (code === null) return "child exited"
  if (code === 0) return "child exited cleanly"
  return `child exited with code ${code}`
}

function isConnectionRefused(err: unknown): boolean {
  if (typeof err === "object" && err !== null) {
    const code = (err as { code?: unknown }).code
    // Bun reports `code: "ConnectionRefused"`; undici/Node report `ECONNREFUSED`.
    if (typeof code === "string" && code.toUpperCase().includes("CONNECTIONREFUSED")) return true
  }
  return /connection refused|CONNECTIONREFUSED|ECONNREFUSED/i.test(String(err))
}

async function waitForExit(proc: Subprocess, ms: number): Promise<boolean> {
  const exited = proc.exited.then(() => true).catch(() => true)
  const deadline = Date.now() + ms
  while (Date.now() < deadline) {
    if (proc.exitCode !== null) return true
    const won = await Promise.race([exited, sleep(25).then(() => false)])
    if (won) return true
  }
  return proc.exitCode !== null
}

async function forceKillTree(pid: number): Promise<void> {
  try {
    await Bun.spawn(["taskkill", "/F", "/T", "/PID", String(pid)], {
      stdout: "ignore",
      stderr: "ignore",
    }).exited
  } catch {
    // taskkill unavailable - nothing further we can do here
  }
}

function parseDiscoveryLine(
  line: string,
): { ok: true; record: Discovery } | { ok: false; diagnostic: Diagnostic } {
  let raw: unknown
  try {
    raw = JSON.parse(line)
  } catch {
    return { ok: false, diagnostic: diag("malformed_discovery", "stdout discovery line is not valid JSON") }
  }
  if (typeof raw !== "object" || raw === null) {
    return { ok: false, diagnostic: diag("malformed_discovery", "stdout discovery record is not an object") }
  }
  const r = raw as Record<string, unknown>
  if (typeof r.port !== "number" || !Number.isInteger(r.port) || r.port <= 0 || r.port > 65535) {
    return { ok: false, diagnostic: diag("malformed_discovery", "discovery record has an invalid port") }
  }
  if (typeof r.service !== "string") {
    return { ok: false, diagnostic: diag("malformed_discovery", "discovery record has an invalid service") }
  }
  if (typeof r.protocol !== "number" || !Number.isInteger(r.protocol)) {
    return { ok: false, diagnostic: diag("malformed_discovery", "discovery record has an invalid protocol") }
  }
  if (r.service !== EXPECTED_SERVICE) {
    return { ok: false, diagnostic: diag("identity_mismatch", "discovery service identity did not match research-graph") }
  }
  if (r.protocol !== EXPECTED_PROTOCOL) {
    return { ok: false, diagnostic: diag("protocol_mismatch", "discovery protocol did not match the supported contract") }
  }
  return {
    ok: true,
    record: {
      port: r.port,
      service: r.service,
      version: typeof r.version === "string" ? r.version : "",
      protocol: r.protocol,
    },
  }
}

/**
 * Bounded line reader over the child's piped stdout. The first non-empty line
 * MUST be the discovery record; any later non-empty line is an extra-record
 * warning. Byte growth is capped at `budget`. Never echoes line contents.
 */
function readDiscovery(
  child: Child,
  budget: number,
  onRecord: (record: Discovery) => void,
  onWarning: (diagnostic: Diagnostic) => void,
  onError: (diagnostic: Diagnostic) => void,
): void {
  const stream = child.proc.stdout
  if (typeof stream !== "object" || stream === null) {
    onError(diag("malformed_discovery", "managed child has no piped stdout"))
    return
  }
  const reader = stream.getReader()
  const decoder = new TextDecoder()
  let buffer = ""
  let found = false
  ;(async () => {
    try {
      for (;;) {
        const { value, done } = await reader.read()
        if (done) break
        buffer += decoder.decode(value, { stream: true })
        if (buffer.length > budget) {
          onError(diag("discovery_too_large", `stdout exceeded ${budget} bytes before a discovery record`))
          return
        }
        for (;;) {
          const nl = buffer.indexOf("\n")
          if (nl < 0) break
          const line = buffer.slice(0, nl).trim()
          buffer = buffer.slice(nl + 1)
          if (!line) continue
          if (found) {
            onWarning(diag("extra_discovery_record", "additional stdout content after the discovery record"))
            continue
          }
          const parsed = parseDiscoveryLine(line)
          if (!parsed.ok) {
            onError(parsed.diagnostic)
            return
          }
          found = true
          onRecord(parsed.record)
        }
      }
      if (!found) {
        onError(
          buffer.trim()
            ? diag("discovery_eof", "stdout closed with unparsed trailing data")
            : diag("discovery_eof", "stdout closed before a discovery record"),
        )
      }
    } catch {
      if (!found) onError(diag("discovery_eof", "stdout read failed"))
    } finally {
      reader.releaseLock()
    }
  })()
}

function isDiscoveryFailure(diagnostic: Diagnostic): boolean {
  return (
    diagnostic.code === "discovery_timeout" ||
    diagnostic.code === "discovery_eof" ||
    diagnostic.code === "malformed_discovery" ||
    diagnostic.code === "discovery_too_large"
  )
}

class Supervisor implements ResearchGraphSupervisor {
  #state: SupervisorState = "idle"
  #generation = 0
  #child: Child | null = null
  #endpoint: Endpoint | null = null
  #mode: "managed" | "external" | null = null
  #startPromise: Promise<StartResult> | null = null
  #stopPromise: Promise<void> | null = null
  #lastExit: Exit | null = null
  #lastProbe: Diagnostic | null = null
  #warnings: Diagnostic[] = []
  #legacyWarned = false
  #lastSetApi: string | null = null
  #secrets = new Set<string>()
  #startedAt: number | null = null

  bind(): void {
    if (process.env.RESEARCH_GRAPH_DISABLE === "1") return
    process.env.RESEARCH_GRAPH_MODE ||= "local"
  }

  start(): Promise<StartResult> {
    if (this.#state === "ready" && this.#endpoint && this.#child?.proc.exitCode === null) {
      return Promise.resolve({ ok: true, endpoint: this.#endpoint, mode: this.#mode! })
    }
    if (this.#state === "starting" && this.#startPromise) return this.#startPromise
    return this.#begin()
  }

  async stop(): Promise<void> {
    if (this.#state === "stopping" && this.#stopPromise) {
      await this.#stopPromise
      return
    }
    if (this.#state === "starting" && this.#startPromise) {
      await this.#startPromise.catch(() => null)
    }
    const child = this.#child
    if (!child) {
      this.#endpoint = null
      this.#state = "idle"
      return
    }
    const gen = child.generation
    this.#state = "stopping"
    this.#stopPromise = this.#stopChild(child, gen)
    try {
      await this.#stopPromise
    } finally {
      this.#stopPromise = null
    }
  }

  snapshot(): SupervisorSnapshot {
    return {
      state: this.#state,
      generation: this.#generation,
      // The snapshot is the diagnostics surface: never expose the live token.
      endpoint: this.#endpoint ? { ...this.#endpoint, token: REDACTED } : null,
      lastExit: this.#lastExit ? { ...this.#lastExit } : null,
      lastProbe: this.#lastProbe ? { ...this.#lastProbe } : null,
      warnings: [...this.#warnings],
    }
  }

  /** Stamp a diagnostic with lifecycle context (state, endpoint, elapsed, exit). */
  #record(d: Diagnostic, origin?: string): Diagnostic {
    return {
      ...d,
      state: this.#state,
      endpoint: d.endpoint ?? origin ?? this.#endpoint?.origin,
      elapsedMs: this.#startedAt === null ? undefined : Date.now() - this.#startedAt,
      lastExit: this.#lastExit ? { ...this.#lastExit } : null,
    }
  }

  /** Redact every known secret (current + env) out of diagnostic text. */
  #scrub(text: string): string {
    const secrets = new Set<string>(this.#secrets)
    const managed = process.env.RESEARCH_GRAPH_MANAGED_CAPABILITY
    const token = process.env.RESEARCH_GRAPH_TOKEN
    if (managed) secrets.add(managed)
    if (token) secrets.add(token)
    return redact(text, secrets)
  }

  async #begin(): Promise<StartResult> {
    if (this.#state === "stopping") await this.stop()
    if (this.#state === "starting" && this.#startPromise) return this.#startPromise
    if (this.#state === "ready" && this.#endpoint && this.#child?.proc.exitCode === null) {
      return { ok: true, endpoint: this.#endpoint, mode: this.#mode! }
    }
    this.#state = "starting"
    this.#generation += 1
    this.#startedAt = Date.now()
    const gen = this.#generation
    const deadline = Date.now() + this.#timeoutMs()
    const startPromise = this.#doStart(gen, deadline)
    this.#startPromise = startPromise
    return startPromise
  }

  #timeoutMs(): number {
    return resolveReadyTimeoutMs(process.env.RESEARCH_GRAPH_READY_TIMEOUT_MS)
  }

  async #doStart(gen: number, deadline: number): Promise<StartResult> {
    if (process.env.RESEARCH_GRAPH_DISABLE === "1") {
      const diagnostic = diag("disabled", "Research Graph is disabled via RESEARCH_GRAPH_DISABLE=1")
      this.#endpoint = null
      this.#state = "idle"
      this.#lastProbe = this.#record(diagnostic)
      return { ok: false, diagnostic: this.#lastProbe }
    }
    // RESEARCH_GRAPH_API may still hold the value WE set on a previous managed
    // adopt; only an operator-set (different) value selects external adoption.
    const external = process.env.RESEARCH_GRAPH_API
    if (external && external !== this.#lastSetApi) {
      return this.#adoptExternal(gen, deadline, external)
    }
    if (this.#lastSetApi !== null) {
      delete process.env.RESEARCH_GRAPH_API
      delete process.env.RESEARCH_GRAPH_TOKEN
      this.#lastSetApi = null
    }
    return this.#doManaged(gen, deadline)
  }

  async #adoptExternal(gen: number, deadline: number, origin: string): Promise<StartResult> {
    const token = process.env.RESEARCH_GRAPH_TOKEN ?? ""
    if (token) this.#secrets.add(token)
    const normalized = origin.replace(/\/+$/, "")
    try {
      const endpoint = await this.#pollHealth(normalized, token, deadline, null)
      this.#adopt(endpoint, gen, "external")
      return { ok: true, endpoint, mode: "external" }
    } catch (err) {
      const diagnostic = asDiagnostic(err, this.#scrub)
      if (gen === this.#generation) {
        this.#endpoint = null
        this.#state = "failed"
        this.#lastProbe = this.#record(diagnostic)
      }
      return { ok: false, diagnostic: this.#record(diagnostic) }
    }
  }

  async #doManaged(gen: number, deadline: number): Promise<StartResult> {
    const cap = generateCapability()
    this.#secrets.add(cap)
    const bin = this.#binary()
    if (!bin) {
      const diagnostic = diag("no_binary", "Research Graph binary not found (set RESEARCH_GRAPH_BIN to point at it)")
      this.#endpoint = null
      this.#state = "idle"
      this.#lastProbe = this.#record(diagnostic)
      return { ok: false, diagnostic: this.#lastProbe }
    }
    let child: Child
    try {
      child = this.#spawnManaged(bin, cap, false)
    } catch (err) {
      const diagnostic = asDiagnostic(err, this.#scrub)
      this.#endpoint = null
      this.#state = "failed"
      this.#lastProbe = this.#record(diagnostic)
      return { ok: false, diagnostic: this.#lastProbe }
    }
    this.#child = child
    this.#lastProbe = null
    this.#watchExit(child)
    try {
      const discovery = await this.#awaitDiscovery(child, deadline)
      const origin = `http://127.0.0.1:${discovery.port}`
      const endpoint = await this.#pollHealth(origin, cap, deadline, child)
      this.#adopt(endpoint, gen, "managed")
      return { ok: true, endpoint, mode: "managed" }
    } catch (err) {
      const diagnostic = asDiagnostic(err, this.#scrub)
      const legacy = await this.#tryLegacy(gen, cap, child, diagnostic)
      if (legacy) return legacy
      await this.#killChild(child)
      if (gen === this.#generation) {
        this.#child = null
        this.#endpoint = null
        if (this.#state !== "ready") this.#state = "failed"
        this.#lastProbe = this.#record(diagnostic)
      }
      return { ok: false, diagnostic: this.#record(diagnostic) }
    }
  }

  #binary(): string | null {
    const name = process.platform === "win32" ? "research-graph.exe" : "research-graph"
    const home = process.env.LOCALAPPDATA || process.env.HOME || ""
    const candidates = [
      path.join(path.dirname(process.execPath), name),
      path.join(process.cwd(), name),
      path.join(home, "MedHorizon", name),
      path.join(home, ".local", "medhorizon", name),
      process.env.RESEARCH_GRAPH_BIN || "",
    ].filter(Boolean)
    return candidates.find((p) => existsSync(p)) ?? null
  }

  #spawnManaged(bin: string, cap: string, fixedPort: boolean): Child {
    const env: Record<string, string | undefined> = { ...process.env }
    env.RESEARCH_GRAPH_MANAGED_CAPABILITY = cap
    env.APP_ENV = env.APP_ENV || "development"
    env.BACKEND_HOST = "127.0.0.1"
    if (fixedPort) env.BACKEND_PORT = String(LEGACY_FIXED_PORT)
    // The managed child derives its own loopback port; never leak the parent's
    // routing or external token into its environment.
    delete env.RESEARCH_GRAPH_API
    delete env.RESEARCH_GRAPH_TOKEN
    const command = /\.(ts|js|mjs|cjs|bun)$/i.test(bin) ? [process.execPath, bin] : [bin]
    const proc = Bun.spawn(command, {
      cwd: path.dirname(bin),
      stdout: "pipe",
      stderr: "ignore",
      env,
    })
    proc.unref()
    return { proc, generation: this.#generation }
  }

  #watchExit(child: Child): void {
    child.proc.exited
      .then((code) => this.#onExit(child, code))
      .catch(() => this.#onExit(child, null))
  }

  #onExit(child: Child, code: number | null): void {
    if (child.generation !== this.#generation) return
    if (this.#child !== child) return
    this.#lastExit = { code, signal: null }
    const stopping = this.#state === "stopping"
    this.#endpoint = null
    this.#child = null
    if (stopping) return // the stop flow owns final cleanup
    this.#clearOwnedEnv()
    if (this.#state === "ready" || this.#state === "starting") {
      this.#state = "exited"
      this.#lastProbe = this.#record(diag("child_exited", exitDescription(code)))
    }
  }

  async #awaitDiscovery(child: Child, deadline: number): Promise<Discovery> {
    return new Promise<Discovery>((resolve, reject) => {
      let done = false
      const timer = setTimeout(() => {
        if (done) return
        done = true
        reject(diag("discovery_timeout", "no discovery record before the readiness deadline"))
      }, Math.max(0, deadline - Date.now()))
      const fail = (d: Diagnostic) => {
        if (done) return
        done = true
        clearTimeout(timer)
        reject(d)
      }
      readDiscovery(
        child,
        DISCOVERY_BYTE_BUDGET,
        (record) => {
          if (done) return
          done = true
          clearTimeout(timer)
          resolve(record)
        },
        (d) => this.#pushWarning(d),
        fail,
      )
    })
  }

  async #pollHealth(origin: string, token: string, deadline: number, child: Child | null): Promise<Endpoint> {
    const headers: Record<string, string> = {}
    if (token) headers.Authorization = `Bearer ${token}`
    for (;;) {
      if (child && this.#child !== child) {
        throw this.#record(
          diag("child_exited", this.#lastExit ? exitDescription(this.#lastExit.code) : "child exited during startup"),
          origin,
        )
      }
      if (Date.now() >= deadline) {
        throw (
          this.#lastProbe ??
          this.#record(diag("health_check_failed", "readiness deadline reached while polling health"), origin)
        )
      }
      let res: Response
      try {
        res = await fetch(`${origin}/health`, {
          headers,
          signal: AbortSignal.timeout(HEALTH_POLL_TIMEOUT_MS),
        })
      } catch (err) {
        this.#lastProbe = this.#record(
          isConnectionRefused(err)
            ? diag("connection_refused", "Research Graph is not yet accepting connections")
            : diag("health_check_failed", this.#scrub(sanitize(String(err)))),
          origin,
        )
        await sleep(HEALTH_POLL_MS)
        continue
      }
      if (res.status === 401 || res.status === 403) {
        throw this.#record(diag("capability_rejected", "Research Graph rejected the bearer capability or token"), origin)
      }
      if (!res.ok) {
        this.#lastProbe = this.#record(diag("health_check_failed", `health endpoint returned HTTP ${res.status}`), origin)
        await sleep(HEALTH_POLL_MS)
        continue
      }
      let body: Record<string, unknown>
      try {
        const raw: unknown = await res.json()
        body = typeof raw === "object" && raw !== null ? (raw as Record<string, unknown>) : {}
      } catch {
        this.#lastProbe = this.#record(diag("health_check_failed", "health endpoint returned non-JSON"), origin)
        await sleep(HEALTH_POLL_MS)
        continue
      }
      if (body.service !== EXPECTED_SERVICE) {
        throw this.#record(diag("identity_mismatch", "health endpoint service identity did not match research-graph"), origin)
      }
      if (body.protocol !== EXPECTED_PROTOCOL) {
        throw this.#record(diag("protocol_mismatch", "health endpoint protocol did not match the supported contract"), origin)
      }
      return {
        origin,
        api: origin,
        token,
        service: EXPECTED_SERVICE,
        version: typeof body.version === "string" ? body.version : "",
        protocol: EXPECTED_PROTOCOL,
      }
    }
  }

  #adopt(endpoint: Endpoint, gen: number, mode: "managed" | "external"): void {
    if (gen !== this.#generation) return
    this.#endpoint = endpoint
    this.#state = "ready"
    this.#mode = mode
    this.#lastProbe = null
    // Only managed adopts own the routing env; external origin is the operator's.
    this.#lastSetApi = mode === "managed" ? endpoint.origin : null
    process.env.RESEARCH_GRAPH_API = endpoint.origin
    if (endpoint.token) process.env.RESEARCH_GRAPH_TOKEN = endpoint.token
    else delete process.env.RESEARCH_GRAPH_TOKEN
    const noun = mode === "external" ? "external sidecar" : "sidecar"
    UI.println(UI.Style.TEXT_INFO_BOLD + "  Research Graph", UI.Style.TEXT_NORMAL, this.#scrub(`${noun} + plugin → ${endpoint.origin}`))
  }

  /**
   * Explicit, time-limited legacy fallback: only after a DISCOVERY failure and
   * only when RESEARCH_GRAPH_LEGACY_FIXED_PORT=1. Tries to adopt the fixed-port
   * (8000) binary through the SAME strict identity/protocol/capability
   * handshake - never "any 2xx on 8000 is healthy". Removed in MedHorizon v0.5.0.
   */
  async #tryLegacy(gen: number, cap: string, firstChild: Child | null, prior: Diagnostic): Promise<StartResult | null> {
    if (process.env.RESEARCH_GRAPH_LEGACY_FIXED_PORT !== "1") return null
    if (!isDiscoveryFailure(prior)) return null
    this.#warnLegacy()
    const origin = `http://127.0.0.1:${LEGACY_FIXED_PORT}`
    const deadline = Date.now() + this.#timeoutMs()
    // An old binary we spawned may already be serving the strict handshake on
    // the fixed port - adopt it without a second spawn.
    if (firstChild && firstChild.proc.exitCode === null) {
      try {
        const endpoint = await this.#pollHealth(origin, cap, deadline, firstChild)
        this.#adopt(endpoint, gen, "managed")
        return { ok: true, endpoint, mode: "managed" }
      } catch {
        // not our legacy service on the fixed port - fall through to a spawn
      }
    }
    await this.#killChild(firstChild)
    const bin = this.#binary()
    if (!bin) {
      const diagnostic = diag("no_binary", "Research Graph binary not found (set RESEARCH_GRAPH_BIN to point at it)")
      this.#endpoint = null
      this.#state = "failed"
      this.#lastProbe = this.#record(diagnostic)
      return { ok: false, diagnostic: this.#lastProbe }
    }
    let child: Child
    try {
      child = this.#spawnManaged(bin, cap, true)
    } catch (err) {
      const diagnostic = asDiagnostic(err, this.#scrub)
      this.#endpoint = null
      this.#state = "failed"
      this.#lastProbe = this.#record(diagnostic)
      return { ok: false, diagnostic: this.#lastProbe }
    }
    this.#child = child
    this.#lastProbe = null
    this.#watchExit(child)
    try {
      const endpoint = await this.#pollHealth(origin, cap, deadline, child)
      this.#adopt(endpoint, gen, "managed")
      return { ok: true, endpoint, mode: "managed" }
    } catch (err) {
      const diagnostic = asDiagnostic(err, this.#scrub)
      await this.#killChild(child)
      if (gen === this.#generation) {
        this.#child = null
        this.#endpoint = null
        if (this.#state !== "ready") this.#state = "failed"
        this.#lastProbe = this.#record(diagnostic)
      }
      return { ok: false, diagnostic: this.#record(diagnostic) }
    }
  }

  #warnLegacy(): void {
    if (this.#legacyWarned) return
    this.#legacyWarned = true
    this.#pushWarning(
      diag("legacy_fallback", `legacy fixed-port fallback active; RESEARCH_GRAPH_LEGACY_FIXED_PORT is removed in MedHorizon ${LEGACY_REMOVAL_VERSION}`),
    )
    UI.println(UI.Style.TEXT_WARNING_BOLD + "  ⚠ Research Graph legacy binary fallback active", UI.Style.TEXT_NORMAL)
    UI.println(UI.Style.TEXT_DIM, this.#scrub(`  RESEARCH_GRAPH_LEGACY_FIXED_PORT will be removed in MedHorizon ${LEGACY_REMOVAL_VERSION}.`))
  }

  #pushWarning(d: Diagnostic): void {
    this.#warnings.push(d)
    if (this.#warnings.length > WARNINGS_MAX) this.#warnings.shift()
  }

  async #killChild(child: Child | null): Promise<void> {
    if (!child) return
    if (child.proc.exitCode !== null) return
    try {
      child.proc.kill()
    } catch {
      // already exited
    }
    await waitForExit(child.proc, KILL_REAP_MS)
  }

  async #stopChild(child: Child, gen: number): Promise<void> {
    const proc = child.proc
    if (process.platform === "win32") {
      try {
        proc.kill()
      } catch {
        // already exited
      }
      if (await waitForExit(proc, STOP_GRACE_MS)) return this.#finishStop(gen)
      await forceKillTree(proc.pid)
      await waitForExit(proc, STOP_FALLBACK_MS)
      return this.#finishStop(gen)
    }
    try {
      proc.kill("SIGTERM")
    } catch {
      // already exited
    }
    if (await waitForExit(proc, STOP_GRACE_MS)) return this.#finishStop(gen)
    try {
      proc.kill("SIGKILL")
    } catch {
      // already exited
    }
    await waitForExit(proc, STOP_FALLBACK_MS)
    return this.#finishStop(gen)
  }

  #finishStop(gen: number): void {
    if (gen !== this.#generation) return
    this.#child = null
    this.#endpoint = null
    this.#state = "idle"
    this.#clearOwnedEnv()
  }

  /**
   * Drop the routing env a MANAGED adopt wrote (RESEARCH_GRAPH_API / _TOKEN),
   * so a stopped or crashed session never leaks a stale endpoint into a later
   * instance (which would misread it as an operator-set external API). An
   * external adoption never writes #lastSetApi, so its operator-owned env is
   * left untouched.
   */
  #clearOwnedEnv(): void {
    if (this.#lastSetApi === null) return
    this.#lastSetApi = null
    delete process.env.RESEARCH_GRAPH_API
    delete process.env.RESEARCH_GRAPH_TOKEN
  }
}

/** Isolated supervisor factory - one instance per caller or test. */
export function createResearchGraphSupervisor(): ResearchGraphSupervisor {
  return new Supervisor()
}

const singleton: ResearchGraphSupervisor = createResearchGraphSupervisor()

/** Bind Research Graph env for the built-in plugin (idempotent). */
export function bindResearchGraph(): void {
  singleton.bind()
}

/** Start the process-wide Research Graph sidecar supervisor. */
export function startResearchGraphSidecar(): Promise<StartResult> {
  return singleton.start()
}

/** Stop the process-wide Research Graph sidecar supervisor (idempotent). */
export function stopResearchGraphSidecar(): Promise<void> {
  return singleton.stop()
}

// Run at import time so Config/Plugin see RESEARCH_GRAPH_* before first load.
bindResearchGraph()
